transportation items:
	elytra¦s = minecraft:elytra
	saddle¦s = minecraft:saddle
	carrot[s] on [a] stick¦s = minecraft:carrot_on_a_stick

old oak boat:
	minecraft version = 1.12.2 or older
	oak boat¦s = minecraft:boat[relatedEntity=oak boat]

new oak boat:
	minecraft version = 1.13 or newer
	oak boat¦s = minecraft:oak_boat[relatedEntity=oak boat]

boats:
	spruce boat¦s = minecraft:spruce_boat[relatedEntity=spruce boat]
	birch boat¦s = minecraft:birch_boat[relatedEntity=birch boat]
	jungle boat¦s = minecraft:jungle_boat[relatedEntity=jungle boat]
	acacia boat¦s = minecraft:acacia_boat[relatedEntity=acacia boat]
	dark oak boat¦s = minecraft:dark_oak_boat[relatedEntity=dark oak boat]

	[any] boat¦s = oak boat, spruce boat, birch boat, jungle boat, acacia boat, dark oak boat

minecarts:
	[normal] minecart¦s = minecraft:minecart[relatedEntity=minecart]

	minecart[s] with chest¦s = minecraft:chest_minecart
	storage minecart¦s = minecart with chest[relatedEntity=minecart with chest]

	minecart[s] with furnace¦s = minecraft:furnace_minecart
	powered minecart¦s = minecart with furnace[relatedEntity=powered minecart]

	minecart[s] with tnt¦s = minecraft:tnt_minecart[relatedEntity=explosive minecart]
	minecart[s] with hopper¦s = minecraft:hopper_minecart[relatedEntity=hopper minecart]
	minecart[s] with command block¦s = minecraft:command_block_minecart

	any minecart¦s = minecart, minecart with chest, minecart with furnace, minecart with tnt, minecart with hopper, minecart with command block

rails before flattening:
	minecraft version = 1.12.2 or older
	{rail straight}:
		{default} = - {Damage:0}
		[(flat|straight)] (north-south|south-north) = - {Damage:0}
		[(flat|straight)] (east-west|west-east) = - {Damage:1}
		(ascending east|descending west) = - {Damage:2}
		(ascending west|descending east) = - {Damage:3}
		(ascending north|descending south) = - {Damage:4}
		(ascending south|descending north) = - {Damage:5}

	{rail powered}:
		{default} = - {Damage:8}
		(powered|active) [(flat|straight)] (north-south|south-north) = - {Damage:8}
		(powered|active) [(flat|straight)] (east-west|west-east) = - {Damage:9}
		(powered|active) (ascending east|descending west) = - {Damage:10}
		(powered|active) (ascending west|descending east) = - {Damage:11}
		(powered|active) (ascending north|descending south) = - {Damage:12}
		(powered|active) (ascending south|descending north) = - {Damage:13}

	{rail curve}:
		{default} = - {Damage:9}
		[curved] (south-east|east-south) = - {Damage:6}
		[curved] (south-west|west-south) = - {Damage:7}
		[curved] (north-west|west-north) = - {Damage:8}
		[curved] (north-east|east-north) = - {Damage:9}

	# Powered Rail
	({rail straight}|{rail powered}) (golden|powered) [minecart] (rail|track)¦s = minecraft:golden_rail
	(golden|powered) [minecart] (rail|track) item¦s = minecraft:golden_rail

	# Detector Rail
	({rail straight}|{rail powered}) detector [minecart] (rail|track)¦s = minecraft:detector_rail
	detector [minecart] (rail|track) item¦s = minecraft:detector_rail

	# Activator rail
	({rail straight}|{rail powered}) activator [minecart] (rail|track)¦s = minecraft:activator_rail
	activator [minecart] (rail|track) item¦s = minecraft:activator_rail

rails after flattening:
	minecraft version = 1.13 or newer

	{rail straight}:
		{default} = -
		[(flat|straight)] (north-south|south-north) = -[shape=north_south]
		[(flat|straight)] (east-west|west-east) = -[shape=east_west]
		(ascending north|descending south) = -[shape=ascending_north]
		(ascending south|descending north) = -[shape=ascending_south]
		(ascending east|descending west) = -[shape=ascending_east]
		(ascending west|descending east) = -[shape=ascending_west]

	{rail curve}:
		{default} = -
		[curved] (north-east|east-north) = -[shape=north_east]
		[curved] (north-west|west-north) = -[shape=north_west]
		[curved] (south-east|east-south) = -[shape=south_east]
		[curved] (south-west|west-south) = -[shape=south_west]

	# Powered Rail
	{powerable} {rail straight} (golden|powered) [minecart] (rail|track)¦s = minecraft:powered_rail
	(golden|powered) [minecart] (rail|track) item¦s = minecraft:powered_rail

	# Detector Rail
	{powerable} {rail straight} detector [minecart] (rail|track)¦s = minecraft:detector_rail
	detector [minecart] (rail|track) item¦s = minecraft:detector_rail

	# Activator rail
	{powerable} {rail straight} activator [minecart] (rail|track)¦s = minecraft:activator_rail
	activator [minecart] (rail|track) item¦s = minecraft:activator_rail

# Rails whose IDs were never changed and whose version differences can be defined by variations.
unchanged rails:
	[({rail straight}|{rail curve})] [normal] [minecart] (rail|track) [block]¦s = minecraft:rail
	(ascending|descending|inclined) [normal] [minecart] (rail|track) [block]¦s = ascending north rail, ascending south rail, ascending east rail, ascending west rail
	curved [normal] [minecart] (rail|track) [block]¦s = north-east rail, north-west rail, south-east rail, south-west rail
	[minecart] (rail|track) item¦s = minecraft:rail

nether update:
	minecraft version = 1.16 or newer

	warped fungus on a stick¦s = minecraft:warped_fungus_on_a_stick
